-- MySQL Script generated by MySQL Workbench
-- Tue Jul 16 08:03:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema literalura
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `literalura` ;

-- -----------------------------------------------------
-- Schema literalura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `literalura` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `literalura` ;

-- -----------------------------------------------------
-- Table `literalura`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `literalura`.`livro` (
  `livroid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`livroid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `literalura`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `literalura`.`subjects` (
  `subjectsid` INT NOT NULL AUTO_INCREMENT,
  `nomeassunto` VARCHAR(45) NOT NULL,
  `livroid` INT NOT NULL,
  PRIMARY KEY (`subjectsid`),
  INDEX `fk_subjects_livro_idx` (`livroid` ASC) VISIBLE,
  CONSTRAINT `fk_subjects_livro`
    FOREIGN KEY (`livroid`)
    REFERENCES `literalura`.`livro` (`livroid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `literalura`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `literalura`.`persons` (
  `personsid` INT NOT NULL,
  `nomepessoa` VARCHAR(45) NOT NULL,
  `livroid` INT NOT NULL,
  PRIMARY KEY (`personsid`),
  INDEX `fk_persons_livro1_idx` (`livroid` ASC) VISIBLE,
  CONSTRAINT `fk_persons_livro1`
    FOREIGN KEY (`livroid`)
    REFERENCES `literalura`.`livro` (`livroid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `literalura`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `literalura`.`cargo` (
  `cargoid` INT NOT NULL AUTO_INCREMENT,
  `nomecargo` VARCHAR(45) NOT NULL,
  `personsid` INT NOT NULL,
  PRIMARY KEY (`cargoid`),
  INDEX `fk_cargo_persons1_idx` (`personsid` ASC) VISIBLE,
  CONSTRAINT `fk_cargo_persons1`
    FOREIGN KEY (`personsid`)
    REFERENCES `literalura`.`persons` (`personsid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Cargo: autor, tradutor';


-- -----------------------------------------------------
-- Table `literalura`.`bookshelves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `literalura`.`bookshelves` (
  `bookshelvesid` INT NOT NULL AUTO_INCREMENT,
  `nomebookshelves` VARCHAR(45) NULL,
  `livroid` INT NOT NULL,
  PRIMARY KEY (`bookshelvesid`),
  INDEX `fk_bookshelves_livro1_idx` (`livroid` ASC) VISIBLE,
  CONSTRAINT `fk_bookshelves_livro1`
    FOREIGN KEY (`livroid`)
    REFERENCES `literalura`.`livro` (`livroid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Patreleiras para livros. A shelf on which books can be stored.';


-- -----------------------------------------------------
-- Table `literalura`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `literalura`.`languages` (
  `languagesid` INT NOT NULL AUTO_INCREMENT,
  `nomelanguages` VARCHAR(45) NULL,
  `livroid` INT NOT NULL,
  PRIMARY KEY (`languagesid`),
  INDEX `fk_languages_livro1_idx` (`livroid` ASC) VISIBLE,
  CONSTRAINT `fk_languages_livro1`
    FOREIGN KEY (`livroid`)
    REFERENCES `literalura`.`livro` (`livroid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
